# 第4章 pandas 数据分析

本 Notebook 按课件的12节顺序组织，从头运行即可完成全章。先预测小表的结果，再运行、修改并核对；每节练习的参考答案可折叠展开。

**数据**：主线为茅台、五粮液和平安的教学合成行情，先用3个日期，再扩充到6个日期。订单合并和成绩清洗是课件中的独立练习；最后用同三只股票的250期合成价格练习风险统计。所有合成数据均不代表实际行情或真实个人信息。

教材配套 `data/eod_data.csv` 只在读写小节使用。无需联网下载；运行产物写入本章 `outputs/`。

## 1. 初识 pandas 与运行准备

Series 是带标签的一列数据，DataFrame 是带行列标签的表。选用课程 `.venv` 内核，按顺序运行。路径支持从课程根目录、本章目录或本章 notebooks 目录启动。

In [1]:
from pathlib import Path
from io import StringIO
import numpy as np
import pandas as pd
from IPython.display import display

cwd = Path.cwd()
if cwd.name == "notebooks":
    CHAPTER = cwd.parent
elif cwd.name == "Chapter4 - pandas数据分析":
    CHAPTER = cwd
else:
    CHAPTER = cwd / "Chapter4 - pandas数据分析"
DATA = CHAPTER / "data"
OUTPUTS = CHAPTER / "outputs"
OUTPUTS.mkdir(exist_ok=True)
pd.set_option("display.max_rows", 20)
pd.set_option("display.unicode.east_asian_width", True)
print("pandas", pd.__version__)

pandas 2.3.3

## 2. Series：标签、取值与自动对齐

### 带标签的价格

代码作为字符串保存；一列也能做向量化运算。

In [2]:
s = pd.Series([1500.35, 128.60, 55.20], index=["600519", "000858", "601318"])
display(s)
display(s[s > 100])
display(s * 1.05)

600519    1500.35
000858     128.60
601318      55.20
dtype: float64

600519    1500.35
000858     128.60
dtype: float64

600519    1575.3675
000858     135.0300
601318      57.9600
dtype: float64

### 按标签匹配，不按位置匹配

先手算 A、B 的结果，再比较 pandas 和 NumPy。缺少 C 的加分时，结果为 NaN，不会自动补零。

In [3]:
base = pd.Series([10, 20], index=["A", "B"])
bonus = pd.Series([1, 2], index=["B", "A"])

display(base + bonus)

base_np = np.array([10, 20])
bonus_np = np.array([1, 2])
display(base_np + bonus_np)

base = pd.Series([10, 20, 30],
                 index=["A", "B", "C"])
bonus = pd.Series([1, 2],
                  index=["B", "A"])

display(base + bonus)

A    12
B    21
dtype: int64

array([11, 22])

A    12.0
B    21.0
C     NaN
dtype: float64

## 3. DataFrame：每行是什么，列是什么

### 三天股票行情

每行一个日期，每列一只股票；价格单位为元。先显示字符串日期，再在下一节转为日期索引。

In [4]:
data = {"茅台": [1500.0, 1520.0, 1515.0],
        "五粮液": [128.0, 129.5, 127.0],
        "平安": [55.0, 54.5, 56.0]}
df = pd.DataFrame(data,
                  index=["2026-07-01", "2026-07-02", "2026-07-03"])
df

              茅台  五粮液  平安
2026-07-01  1500.0   128.0  55.0
2026-07-02  1520.0   129.5  54.5
2026-07-03  1515.0   127.0  56.0

### 查看结构与摘要

先看行列数、类型及前后记录，再看描述统计。一列 Series 和单列 DataFrame 的维度不同。

In [5]:
display(df.shape)
df.info()
display(df.head(2), df.tail(1))
display(df.describe().round(2))
print(type(df["茅台"]).__name__, df["茅台"].shape)
print(type(df[["茅台"]]).__name__, df[["茅台"]].shape)

(3, 3)

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 2026-07-01 to 2026-07-03
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   茅台      3 non-null      float64
 1   五粮液     3 non-null      float64
 2   平安      3 non-null      float64
dtypes: float64(3)
memory usage: 96.0+ bytes

              茅台  五粮液  平安
2026-07-01  1500.0   128.0  55.0
2026-07-02  1520.0   129.5  54.5

              茅台  五粮液  平安
2026-07-03  1515.0   127.0  56.0

          茅台  五粮液   平安
count     3.00    3.00   3.00
mean   1511.67  128.17  55.17
std      10.41    1.26   0.76
min    1500.00  127.00  54.50
25%    1507.50  127.50  54.75
50%    1515.00  128.00  55.00
75%    1517.50  128.75  55.50
max    1520.00  129.50  56.00

Series (3,)
DataFrame (3, 1)

## 4. 数据选取与筛选

### 日期标签与整数位置

loc 按标签切片，包含两个端点；iloc 按位置切片，不含末端位置。

In [6]:
df.index = pd.to_datetime(df.index)
display(df.loc["2026-07-01":"2026-07-02", ["茅台", "平安"]])
display(df.iloc[0:2, [0, 2]])
display(df.loc["2026-07"])

              茅台  平安
2026-07-01  1500.0  55.0
2026-07-02  1520.0  54.5

              茅台  平安
2026-07-01  1500.0  55.0
2026-07-02  1520.0  54.5

              茅台  五粮液  平安
2026-07-01  1500.0   128.0  55.0
2026-07-02  1520.0   129.5  54.5
2026-07-03  1515.0   127.0  56.0

### 条件筛选与赋值

多条件用 &、| 并加括号。在副本中用 loc 一次指定行列，保留原价格。

In [7]:
display(df.loc[(df["茅台"] > 1500) & (df["平安"] > 55)])
adjusted = df.copy()
adjusted.loc[adjusted["五粮液"] < 128, "五粮液"] = 128
display(adjusted)

              茅台  五粮液  平安
2026-07-03  1515.0   127.0  56.0

              茅台  五粮液  平安
2026-07-01  1500.0   128.0  55.0
2026-07-02  1520.0   129.5  54.5
2026-07-03  1515.0   128.0  56.0

**练习**：只显示五粮液低于128元的日期及其价格。

<details><summary>参考答案（先自己动手）</summary>

```python
df.loc[df["五粮液"] < 128, ["五粮液"]]
```
</details>

## 5. 宽表与长表：扩充同一份行情

### 从3天扩充为6天

沿用同三只股票，平安后3天没有报价。宽表适合横向比较、矩阵运算和逐列计算。

In [8]:
dates = pd.to_datetime([
    "2026-07-01", "2026-07-02", "2026-07-03",
    "2026-07-06", "2026-07-07", "2026-07-08"])
prices_wide = pd.DataFrame({
    "茅台": [1500, 1520, 1515, 1530, 1525, 1545],
    "五粮液": [128, 129.5, 127, 130, 129, 131.2],
    "平安": [55, 54.5, 56, np.nan, np.nan, np.nan]},
    index=dates)
prices_wide.index.name = "日期"
display(prices_wide.shape)

display(prices_wide)

(6, 3)

            茅台  五粮液  平安
日期
2026-07-01  1500   128.0  55.0
2026-07-02  1520   129.5  54.5
2026-07-03  1515   127.0  56.0
2026-07-06  1530   130.0   NaN
2026-07-07  1525   129.0   NaN
2026-07-08  1545   131.2   NaN

### melt 展开，pivot 还原

long_prices 保留全部18个日期—股票组合；market 只有15条有效报价。长表方便追加记录、连接信息和逐组计算。pivot 要求组合键唯一，不进行聚合。

In [9]:
long_prices = prices_wide.reset_index().melt(
    id_vars="日期", var_name="股票", value_name="收盘价")
display(long_prices.shape)
market = long_prices[["股票", "日期", "收盘价"]].dropna(
    subset=["收盘价"])
display(market.shape)

display(market)

restored = long_prices.pivot(
    index="日期", columns="股票", values="收盘价")
restored = restored.reindex(columns=prices_wide.columns)
display(restored)

(18, 3)

(15, 3)

      股票       日期  收盘价
0     茅台 2026-07-01  1500.0
1     茅台 2026-07-02  1520.0
2     茅台 2026-07-03  1515.0
3     茅台 2026-07-06  1530.0
4     茅台 2026-07-07  1525.0
5     茅台 2026-07-08  1545.0
6   五粮液 2026-07-01   128.0
7   五粮液 2026-07-02   129.5
8   五粮液 2026-07-03   127.0
9   五粮液 2026-07-06   130.0
10  五粮液 2026-07-07   129.0
11  五粮液 2026-07-08   131.2
12    平安 2026-07-01    55.0
13    平安 2026-07-02    54.5
14    平安 2026-07-03    56.0

              茅台  五粮液  平安
日期
2026-07-01  1500.0   128.0  55.0
2026-07-02  1520.0   129.5  54.5
2026-07-03  1515.0   127.0  56.0
2026-07-06  1530.0   130.0   NaN
2026-07-07  1525.0   129.0   NaN
2026-07-08  1545.0   131.2   NaN

## 6. 排序与分组

### 排序后再聚合

按股票、日期排序，首末价格才有时间含义。agg 每组一行；命名聚合直接命名输出列。各股票的报价天数不同。

In [10]:
market = market.sort_values(["股票", "日期"])
display(market.head(3))

result = market.groupby("股票")["收盘价"].agg(
    ["count", "mean", "min", "max"])
display(result.round(2))

summary = market.groupby("股票", as_index=False).agg(
    记录数=("日期", "size"),
    平均收盘价=("收盘价", "mean"))
display(summary.round(2))

     股票       日期  收盘价
6  五粮液 2026-07-01   128.0
7  五粮液 2026-07-02   129.5
8  五粮液 2026-07-03   127.0

        count     mean     min     max
股票
五粮液      6   129.12   127.0   131.2
平安        3    55.17    54.5    56.0
茅台        6  1522.50  1500.0  1545.0

     股票  记录数  平均收盘价
0  五粮液       6      129.12
1    平安       3       55.17
2    茅台       6     1522.50

### size、count 与 transform

size 数所有行，count 数有效值；transform 将组均值带回原行。全样本均值不能作为历史时点已知的交易信号。

In [11]:
missing = market.copy()
missing.loc[1, "收盘价"] = float("nan")
counts = missing.groupby("股票").agg(
    记录数=("收盘价", "size"),
    有效价格数=("收盘价", "count"),
    平均收盘价=("收盘价", "mean"))
display(counts.round(2))

relative = market.copy()
relative["样本均价"] = relative.groupby("股票")[
    "收盘价"].transform("mean")
relative["偏离均价"] = relative["收盘价"] - relative["样本均价"]
display(relative.loc[relative["股票"] == "茅台"].round(2))

        记录数  有效价格数  平均收盘价
股票
五粮液       6           6      129.12
平安         3           3       55.17
茅台         6           5     1523.00

   股票       日期  收盘价  样本均价  偏离均价
0  茅台 2026-07-01  1500.0    1522.5     -22.5
1  茅台 2026-07-02  1520.0    1522.5      -2.5
2  茅台 2026-07-03  1515.0    1522.5      -7.5
3  茅台 2026-07-06  1530.0    1522.5       7.5
4  茅台 2026-07-07  1525.0    1522.5       2.5
5  茅台 2026-07-08  1545.0    1522.5      22.5

### 分组循环与整组筛选

循环每次拿到组名和小表；filter 返回满足组条件的全部原始行。至少5条记录不等于覆盖全部应有交易日。

In [12]:
for name, group in market.groupby("股票", sort=False):
    print(name, len(group),
          group["收盘价"].iloc[0],
          group["收盘价"].iloc[-1])

kept = market.groupby("股票", sort=False).filter(
    lambda group: len(group) >= 5)
display(kept.groupby("股票", sort=False).size())
display(kept.shape)

五粮液 6 128.0 131.2
平安 3 55.0 56.0
茅台 6 1500.0 1545.0

股票
五粮液    6
茅台      6
dtype: int64

(12, 3)

### apply 与内置聚合

自定义函数返回每组摘要；能用内置聚合时优先使用。first/last 默认取首末非缺失值，而 iloc 按实际位置取值。

In [13]:
def price_summary(group):
    prices = group["收盘价"]
    return pd.Series({
        "首日价": prices.iloc[0],
        "末日价": prices.iloc[-1],
        "区间涨幅(%)": (prices.iloc[-1] / prices.iloc[0] - 1) * 100})

result = kept.groupby("股票", sort=False)[["收盘价"]].apply(
    price_summary)
display(result.round(2))

result = kept.groupby("股票", sort=False).agg(
    首日价=("收盘价", "first"),
    末日价=("收盘价", "last"))
result["区间涨幅(%)"] = (
    result["末日价"] / result["首日价"] - 1) * 100
display(result.round(2))

        首日价  末日价  区间涨幅(%)
股票
五粮液   128.0   131.2          2.5
茅台    1500.0  1545.0          3.0

        首日价  末日价  区间涨幅(%)
股票
五粮液   128.0   131.2          2.5
茅台    1500.0  1545.0          3.0

**练习**：生成每只股票的记录数、最高价、最低价和价格差；再把 filter 门槛改为3条，说明平安区间涨幅的日期范围。

<details><summary>参考答案（先自己动手）</summary>

```python
price_range = market.groupby("股票", as_index=False).agg(
    记录数=("日期", "size"), 最高价=("收盘价", "max"), 最低价=("收盘价", "min"))
price_range["价格差"] = price_range["最高价"] - price_range["最低价"]
display(price_range)
kept3 = market.groupby("股票").filter(lambda group: len(group) >= 3)
display(kept3.groupby("股票")[["收盘价"]].apply(price_summary))
# 平安只覆盖7月1日至3日，另外两只覆盖7月1日至8日；不能直接比较不同区间。
```
</details>

## 7. 数据清洗基础与缺失值

### 保留原始报价，清理文本并转换类型

这是故意含有问题的报价登记，不覆盖 prices_wide。字符串代码保留前导零；未披露、解析失败和非正价格需要区分。

In [14]:
raw_quotes = pd.DataFrame({
    "代码": [" 600519 ", "600519", "000858", "601318", "600036"],
    "日期": ["2026-07-01"] * 4 + ["待核"],
    "价格文本": ["1500", "1500", "未披露", "-5", "40"]})
display(raw_quotes)

quotes_clean = raw_quotes.copy()
quotes_clean["代码"] = quotes_clean["代码"].str.strip()
display(quotes_clean["代码"].tolist())
display(quotes_clean["代码"].str.startswith("60").tolist())

price_text = quotes_clean["价格文本"].replace("未披露", pd.NA)
quotes_clean["价格"] = pd.to_numeric(price_text, errors="coerce")
quotes_clean["交易日"] = pd.to_datetime(
    quotes_clean["日期"], errors="coerce")
failed = price_text.notna() & quotes_clean["价格"].isna()
display(failed.tolist())
display(quotes_clean[["价格", "交易日"]])

       代码        日期 价格文本
0   600519   2026-07-01     1500
1    600519  2026-07-01     1500
2    000858  2026-07-01   未披露
3    601318  2026-07-01       -5
4    600036        待核       40

['600519', '600519', '000858', '601318', '600036']

[True, True, False, True, True]

[False, False, False, False, False]

     价格     交易日
0  1500.0 2026-07-01
1  1500.0 2026-07-01
2     NaN 2026-07-01
3    -5.0 2026-07-01
4    40.0        NaT

### 识别重复、异常与标签

整行重复确认后可删除；同一键有不同值需核查。map 按字典映射，cut 按区间分段，价格水平不代表估值高低。

In [15]:
display(quotes_clean.duplicated().tolist())
display(quotes_clean.duplicated(
    ["代码", "日期"], keep=False).tolist())
quotes_clean = quotes_clean.drop_duplicates()
display(quotes_clean.index.tolist())

quotes_clean["价格异常"] = quotes_clean["价格"].le(0)
quotes_clean["有效价格"] = quotes_clean["价格"].mask(
    quotes_clean["价格异常"])
display(quotes_clean[["代码", "价格异常", "有效价格"]])

quotes_clean["名称"] = quotes_clean["代码"].map({
    "600519": "茅台", "000858": "五粮液",
    "601318": "平安", "600036": "招行"})
quotes_clean["价格区间"] = pd.cut(
    quotes_clean["有效价格"], bins=[0, 100, 1000, float("inf")],
    right=False, labels=["低于100", "100至不足1000", "至少1000"])
display(quotes_clean[["名称", "价格区间"]])

[False, True, False, False, False]

[True, True, False, False, False]

[0, 2, 3, 4]

     代码  价格异常  有效价格
0  600519     False    1500.0
2  000858     False       NaN
3  601318      True       NaN
4  600036     False      40.0

     名称  价格区间
0    茅台  至少1000
2  五粮液       NaN
3    平安       NaN
4    招行   低于100

### 缺失处理改变了什么

沿用平安报价，比较删除、均值填充、前向填充；填充值不是真实新报价。

In [16]:
pa = prices_wide["平安"]
display(pd.DataFrame({"原值": pa, "缺失标记": pa.isna(),
    "均值填充": pa.fillna(pa.mean()), "前向填充": pa.ffill()}))
display(pa.dropna())

            原值  缺失标记   均值填充  前向填充
日期
2026-07-01  55.0     False  55.000000      55.0
2026-07-02  54.5     False  54.500000      54.5
2026-07-03  56.0     False  56.000000      56.0
2026-07-06   NaN      True  55.166667      56.0
2026-07-07   NaN      True  55.166667      56.0
2026-07-08   NaN      True  55.166667      56.0

日期
2026-07-01    55.0
2026-07-02    54.5
2026-07-03    56.0
Name: 平安, dtype: float64

### 何时可以补零

两个账户清单都已确认完整，未列出表示零持股，此时可用 fill_value=0。未知价格不适用。

In [17]:
account_a = pd.Series({"茅台": 100, "平安": 200})
account_b = pd.Series({"平安": 300, "招行": 400})
total = account_a.add(account_b, fill_value=0)
display(total.reindex(["茅台", "平安", "招行"]))

茅台    100.0
平安    500.0
招行    400.0
dtype: float64

**练习**：筛出价格有效且交易日已知的报价，解释为什么不能只看有效价格。

<details><summary>参考答案（先自己动手）</summary>

```python
quotes_clean.dropna(subset=["有效价格", "交易日"])
# 招行价格40元，但日期待核，不能用于按日计算。
```
</details>

## 8. 数据合并与变形进阶

本节保留课件中的小订单表，便于手算匹配关系；不再另外开展订单分组日报。

### 合并前确定粒度和键

订单表每行一笔订单，商品表每行一种商品。left 保留订单；validate 检查多对一关系，indicator 标记匹配来源。

In [18]:
import pandas as pd
orders = pd.DataFrame({
    "订单": [1, 2, 3, 4], "商品": ["T", "C", "T", "X"],
    "数量": [2, 1, 3, 1]})
products = pd.DataFrame({
    "商品": ["T", "C", "J"],
    "名称": ["茶", "咖啡", "果汁"], "单价": [10, 20, 15]})
display(orders)
display(products)

joined = orders.merge(products, on="商品", how="left",
    validate="many_to_one", indicator=True)
display(joined)
display(joined["_merge"].value_counts())
print("合并前后行数：", len(orders), len(joined))

   订单 商品  数量
0     1    T     2
1     2    C     1
2     3    T     3
3     4    X     1

  商品  名称  单价
0    T    茶    10
1    C  咖啡    20
2    J  果汁    15

   订单 商品  数量  名称  单价     _merge
0     1    T     2    茶  10.0       both
1     2    C     1  咖啡  20.0       both
2     3    T     3    茶  10.0       both
3     4    X     1   NaN   NaN  left_only

_merge
both          3
left_only     1
right_only    0
Name: count, dtype: int64

合并前后行数： 4 4

### 连接方式与重复键

inner 丢掉未匹配订单，outer 还保留仅右侧出现的商品。重复商品键会让订单匹配多次，不能在合并后任意去重。

In [19]:
inner = orders.merge(products, on="商品", how="inner")
outer = orders.merge(products, on="商品", how="outer",
                     indicator=True)
print("内连接、外连接行数：", len(inner), len(outer))
display(inner[["订单", "商品"]])
display(outer[["订单", "商品", "_merge"]])

bad_products = pd.concat([products, products.iloc[[0]]],
                          ignore_index=True)
expanded = orders.merge(bad_products, on="商品", how="left")
print("合并前后行数：", len(orders), len(expanded))
display(expanded[["订单", "商品", "数量", "单价"]])
print("重复商品键数：", bad_products.duplicated("商品").sum())

内连接、外连接行数： 3 5

   订单 商品
0     1    T
1     2    C
2     3    T

   订单 商品      _merge
0   2.0    C        both
1   NaN    J  right_only
2   1.0    T        both
3   3.0    T        both
4   4.0    X   left_only

合并前后行数： 4 6

   订单 商品  数量  单价
0     1    T     2  10.0
1     1    T     2  10.0
2     2    C     1  20.0
3     3    T     3  10.0
4     3    T     3  10.0
5     4    X     1   NaN

重复商品键数： 1

### concat 追加与横向对齐

纵向追加不检查业务键；横向按索引对齐。

In [20]:
next_orders = pd.DataFrame({
    "订单": [5, 6], "商品": ["C", "T"], "数量": [2, 1]})
all_orders = pd.concat([orders, next_orders], ignore_index=True)
display(all_orders)
display(all_orders["订单"].is_unique)

left = pd.Series([80, 90], index=["001", "002"], name="数学")
right = pd.Series([70, 85], index=["002", "001"], name="英语")
display(pd.concat([left, right], axis=1))

   订单 商品  数量
0     1    T     2
1     2    C     1
2     3    T     3
3     4    X     1
4     5    C     2
5     6    T     1

True

     数学  英语
001    80    85
002    90    70

### 重复组合的聚合与多层索引

沿用课件的补考小表：max 回答最高分，mean 回答均分。MultiIndex 显式表达学号—课程组合。宽长转换的入门已在第5节完成。

In [21]:
long_scores = pd.DataFrame({
    "学号": ["001", "001", "002", "002"],
    "课程": ["数学", "英语", "数学", "英语"],
    "成绩": [80, 90, 70, 85]})
retake = pd.DataFrame({"学号": ["002"],
                       "课程": ["数学"], "成绩": [88]})
attempts = pd.concat([long_scores, retake], ignore_index=True)
best = attempts.pivot_table(index="学号", columns="课程",
    values="成绩", aggfunc="max")
display(best)

indexed = long_scores.set_index(["学号", "课程"]).sort_index()
display(indexed)
display(indexed.loc[("001", "数学"), "成绩"])
display(indexed.unstack("课程"))
display(indexed.reset_index())

课程  数学  英语
学号
001     80    90
002     88    85

           成绩
学号 课程
001  数学    80
     英语    90
002  数学    70
     英语    85

np.int64(80)

     成绩
课程 数学 英语
学号
001    80   90
002    70   85

  学号  课程  成绩
0  001  数学    80
1  001  英语    90
2  002  数学    70
3  002  英语    85

### 已知金额与覆盖范围

70元只覆盖已匹配的3笔订单，不能称为全部订单金额。

In [22]:
matched = joined.loc[joined["_merge"] == "both"].copy()
matched["金额"] = matched["数量"] * matched["单价"]
display(matched[["订单", "名称", "金额"]])
print("已知金额合计：", matched["金额"].sum())  # 70
print("未匹配订单数：", (joined["_merge"] == "left_only").sum())

   订单  名称  金额
0     1    茶  20.0
1     2  咖啡  20.0
2     3    茶  30.0

已知金额合计： 70.0
未匹配订单数： 1

**练习**：找出 inner 丢失的订单和仅右表出现的商品；补齐X为5元的水后重新算总金额；比较002数学的最高分与均分。

<details><summary>参考答案（先自己动手）</summary>

```python
display(joined.loc[joined["_merge"] == "left_only", "订单"])
display(outer.loc[outer["_merge"] == "right_only", "商品"])
fixed = pd.concat([products, pd.DataFrame({"商品": ["X"], "名称": ["水"], "单价": [5]})], ignore_index=True)
complete = orders.merge(fixed, on="商品", how="left", validate="many_to_one")
print((complete["数量"] * complete["单价"]).sum())  # 75
average = attempts.pivot_table(index="学号", columns="课程", values="成绩", aggfunc="mean")
print(average.loc["002", "数学"])  # 79；最高分88
```
</details>

## 9. 金融综合应用：行情与样本检查

回到同一份股票行情。long_prices 保留缺失位置，避免删除中间缺价后把跨多日变化误认为相邻观测变化。

### 报价覆盖与组内收益率

size 的应有数量来自保留的18个网格组合。先按股票、日期排序，再与同一股票的前一期配对。

In [23]:
coverage = long_prices.groupby("日期").agg(
    应有股票数=("股票", "size"), 有效报价数=("收盘价", "count"))
coverage["缺失报价数"] = coverage["应有股票数"] - coverage["有效报价数"]
display(coverage)

quote_panel = long_prices.sort_values(["股票", "日期"]).copy()
quote_panel["上一观测日价"] = quote_panel.groupby("股票")["收盘价"].shift(1)
quote_panel["收益率"] = (
    quote_panel["收盘价"] / quote_panel["上一观测日价"] - 1)
display(quote_panel.loc[quote_panel["股票"] == "平安",
    ["日期", "收盘价", "上一观测日价", "收益率"]].round(4))

            应有股票数  有效报价数  缺失报价数
日期
2026-07-01           3           3           0
2026-07-02           3           3           0
2026-07-03           3           3           0
2026-07-06           3           2           1
2026-07-07           3           2           1
2026-07-08           3           2           1

         日期  收盘价  上一观测日价  收益率
12 2026-07-01    55.0           NaN     NaN
13 2026-07-02    54.5          55.0 -0.0091
14 2026-07-03    56.0          54.5  0.0275
15 2026-07-06     NaN          56.0     NaN
16 2026-07-07     NaN           NaN     NaN
17 2026-07-08     NaN           NaN     NaN

### 矩阵与共同样本

展示时乘100转为百分比，存储值仍为小数。有效收益率分别为5、5、2个；共同样本仅两天，只适合演示筛选。

In [24]:
returns = quote_panel.pivot(
    index="日期", columns="股票", values="收益率")
returns = returns.reindex(columns=prices_wide.columns)
display((returns * 100).round(2))

display(returns.count().tolist())
common_returns = returns.dropna(how="any")
display((common_returns * 100).round(2))

            茅台  五粮液  平安
日期
2026-07-01   NaN     NaN   NaN
2026-07-02  1.33    1.17 -0.91
2026-07-03 -0.33   -1.93  2.75
2026-07-06  0.99    2.36   NaN
2026-07-07 -0.33   -0.77   NaN
2026-07-08  1.31    1.71   NaN

[5, 5, 2]

            茅台  五粮液  平安
日期
2026-07-02  1.33    1.17 -0.91
2026-07-03 -0.33   -1.93  2.75

**练习**：在副本中补入平安7月6日55.5元报价，重新计算覆盖与收益率矩阵。共同日期增加哪天？

<details><summary>参考答案（先自己动手）</summary>

```python
expanded_prices = prices_wide.copy()
expanded_prices.loc["2026-07-06", "平安"] = 55.5
expanded_long = expanded_prices.reset_index().melt(id_vars="日期", var_name="股票", value_name="收盘价")
display(expanded_long.groupby("日期").agg(应有股票数=("股票", "size"), 有效报价数=("收盘价", "count")))
expanded_returns = expanded_prices.pct_change(fill_method=None)
display((expanded_returns * 100).round(2))
display(expanded_returns.dropna(how="any").index)
# 新增7月6日；平安收益率55.5/56-1约为-0.89%。7月7日仍无报价。
```
</details>

## 10. 金融时间序列

### 样例与日期索引

继续使用六个日期的行情。B 是周一至周五，不是交易所节假日日历。

In [25]:
pd.set_option("display.unicode.east_asian_width", True)
ts_prices = prices_wide.copy()
display(ts_prices)

display(pd.to_datetime(["2026-07-03", "2026-07-06"]))
bdays = pd.date_range("2026-07-01", periods=6, freq="B")
display(bdays.strftime("%Y-%m-%d").tolist())
display(ts_prices.loc["2026-07-02":"2026-07-03"])

            茅台  五粮液  平安
日期
2026-07-01  1500   128.0  55.0
2026-07-02  1520   129.5  54.5
2026-07-03  1515   127.0  56.0
2026-07-06  1530   130.0   NaN
2026-07-07  1525   129.0   NaN
2026-07-08  1545   131.2   NaN

DatetimeIndex(['2026-07-03', '2026-07-06'], dtype='datetime64[ns]', freq=None)

['2026-07-01',
 '2026-07-02',
 '2026-07-03',
 '2026-07-06',
 '2026-07-07',
 '2026-07-08']

            茅台  五粮液  平安
日期
2026-07-02  1520   129.5  54.5
2026-07-03  1515   127.0  56.0

### Timedelta 与 shift

Timestamp 是时间点，Timedelta 是经过的时间；移动一行与移动日期标签不同。周五加一天会到周六。

In [26]:
gap = pd.Timestamp("2026-07-06") - pd.Timestamp("2026-07-03")
display(gap)
display(pd.Timestamp("2026-07-03") + pd.Timedelta(days=1))
gaps = ts_prices.index.to_series().diff()
display(gaps)

s = ts_prices["茅台"].head(3)
display(pd.DataFrame({"原价": s, "上一行价格": s.shift(1)}))
display(s.shift(1, freq="D"))

Timedelta('3 days 00:00:00')

Timestamp('2026-07-04 00:00:00')

日期
2026-07-01      NaT
2026-07-02   1 days
2026-07-03   1 days
2026-07-06   3 days
2026-07-07   1 days
2026-07-08   1 days
Name: 日期, dtype: timedelta64[ns]

            原价  上一行价格
日期
2026-07-01  1500         NaN
2026-07-02  1520      1500.0
2026-07-03  1515      1520.0

日期
2026-07-02    1500
2026-07-03    1520
2026-07-04    1515
Name: 茅台, dtype: int64

### diff 与 pct_change

价差单位为元，收益率为比例；缺失价格不自动填充。

In [27]:
changes = pd.DataFrame({
    "茅台价差": ts_prices["茅台"].diff(),
    "茅台收益率(%)": ts_prices["茅台"].pct_change(fill_method=None) * 100,
    "平安收益率(%)": ts_prices["平安"].pct_change(fill_method=None) * 100})
display(changes.round(2))

            茅台价差  茅台收益率(%)  平安收益率(%)
日期
2026-07-01       NaN            NaN            NaN
2026-07-02      20.0           1.33          -0.91
2026-07-03      -5.0          -0.33           2.75
2026-07-06      15.0           0.99            NaN
2026-07-07      -5.0          -0.33            NaN
2026-07-08      20.0           1.31            NaN

### 周频下采样

W-FRI 以周五为右端点标签。样本只到7月8日，7月10日标签不代表该日有报价。

In [28]:
weekly_last = ts_prices.resample("W-FRI").last()
display(weekly_last)
display(ts_prices.resample("W-FRI").mean().round(2))

display(ts_prices.resample("W-FRI").count())
display(ts_prices["茅台"].resample("W-FRI").ohlc())

            茅台  五粮液  平安
日期
2026-07-03  1515   127.0  56.0
2026-07-10  1545   131.2   NaN

               茅台  五粮液   平安
日期
2026-07-03  1511.67  128.17  55.17
2026-07-10  1533.33  130.07    NaN

            茅台  五粮液  平安
日期
2026-07-03     3       3     3
2026-07-10     3       3     0

            open  high   low  close
日期
2026-07-03  1500  1520  1500   1515
2026-07-10  1530  1545  1525   1545

日收盘价的 ohlc 只给出周内收盘价的首、最大、最小、末值，不是完整周K线。价格通常不求和；成交量常用 sum。

### 先采样，再算区间收益率

最后有效价格可能来自不同日期。这里只有一个月份，无法得到月间收益率。

In [29]:
weekly_ret = weekly_last.pct_change(fill_method=None)
display((weekly_ret * 100).round(2))
display(ts_prices.resample("ME").last())

            茅台  五粮液  平安
日期
2026-07-03   NaN     NaN   NaN
2026-07-10  1.98    3.31   NaN

            茅台  五粮液  平安
日期
2026-07-31  1545   131.2  56.0

**练习**：补入7月9、10日的行情：茅台1540、1550；五粮液130.5、132；平安56.5、57。输出周末价格、报价数及周频收益率。

<details><summary>参考答案（先自己动手）</summary>

```python
extra = pd.DataFrame({"茅台": [1540, 1550], "五粮液": [130.5, 132], "平安": [56.5, 57]}, index=pd.to_datetime(["2026-07-09", "2026-07-10"]))
full_prices = pd.concat([prices_wide, extra]).sort_index()
display(full_prices.index.to_series().diff())
full_weekly = full_prices.resample("W-FRI").last()
display(full_weekly, full_prices.resample("W-FRI").count())
display((full_weekly.pct_change(fill_method=None) * 100).round(2))
# 第二组仍标记7月10日，末价现在来自7月10日；平安第二周仍仅有2条报价。
```
</details>

## 11. 读写数据

### 导出与读回

CSV 不保留全部类型；读回时解析日期。运行文件写入本章 outputs，不覆盖源数据。

In [30]:
prices_wide.to_csv(OUTPUTS / "demo_prices.csv")
read_back = pd.read_csv(OUTPUTS / "demo_prices.csv", index_col=0, parse_dates=True)
display(read_back)

            茅台  五粮液  平安
日期
2026-07-01  1500   128.0  55.0
2026-07-02  1520   129.5  54.5
2026-07-03  1515   127.0  56.0
2026-07-06  1530   130.0   NaN
2026-07-07  1525   129.0   NaN
2026-07-08  1545   131.2   NaN

### 读取教材配套文件

这是教材本地 eod_data.csv 的预览，列的含义需结合教材说明，不能默认与教学价格表同口径。这里只检查结构和日期范围。

In [31]:
eod = pd.read_csv(DATA / "eod_data.csv", index_col=0, parse_dates=True)
print(eod.shape, eod.index.min(), eod.index.max())
display(eod.head(3))

(2216, 12) 2010-01-01 00:00:00 2018-06-29 00:00:00

,AAPL.O,MSFT.O,INTC.O,AMZN.O,GS.N,SPY,.SPX,.VIX,EUR=,XAU=,GDX,GLD
Date,,,,,,,,,,,,
2010-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.4323,1096.35,NaN,NaN
2010-01-04,30.572827,30.95,20.88,133.90,173.08,113.33,1132.99,20.04,1.4411,1120.00,47.71,109.8
2010-01-05,30.625684,30.96,20.87,134.69,176.14,113.63,1136.52,19.35,1.4368,1118.65,48.17,109.7

## 12. 综合案例与小结

### 12.1 成绩登记清洗练习

与课件最后的综合案例对应：请先自行完成文本规范、类型转换、重复与异常处理、分类及CSV往返，再参考下面的步骤。成绩满分100，缺考不等于0分，异常108分也不能直接改成100。

### 原始登记与检查

每行一次登记，学号按字符串保存。

In [32]:
from io import StringIO
import pandas as pd
raw_csv = """学号,姓名,班级,成绩,日期
001, 小林 ,A,82,2026-09-01
002,小周,a,95,2026-09-01
003,小陈,B,缺考,2026-09-02
004,小许,B,108,2026-09-02
001, 小林 ,A,82,2026-09-01
005,小吴, B ,76,日期待核"""
raw = pd.read_csv(StringIO(raw_csv), dtype="string")
raw

raw.info()
display(raw.isna().sum())
print("整行重复数：", raw.duplicated().sum())
raw.loc[raw.duplicated(keep=False)]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   学号      6 non-null      string
 1   姓名      6 non-null      string
 2   班级      6 non-null      string
 3   成绩      6 non-null      string
 4   日期      6 non-null      string
dtypes: string(5)
memory usage: 372.0 bytes

学号    0
姓名    0
班级    0
成绩    0
日期    0
dtype: int64

整行重复数： 1

  学号    姓名 班级 成绩        日期
0  001   小林     A   82  2026-09-01
4  001   小林     A   82  2026-09-01

### 文本、类型与重复

保留原始文本，区分缺考与解析失败；只删除确认重复的整行。

In [33]:
clean = raw.copy()
clean["姓名"] = clean["姓名"].str.strip()
clean["班级"] = clean["班级"].str.strip().str.upper()
display(clean["班级"].value_counts())
display(clean["姓名"].str.contains("小", na=False))

score_text = clean["成绩"].replace("缺考", pd.NA)
clean["分数"] = pd.to_numeric(score_text, errors="coerce")
clean["登记日"] = pd.to_datetime(clean["日期"], errors="coerce")
parse_failed = score_text.notna() & clean["分数"].isna()
display(clean.loc[parse_failed | clean["登记日"].isna()])
display(clean.dtypes)

display(clean.loc[clean.duplicated("学号", keep=False)])
clean = clean.drop_duplicates().reset_index(drop=True)
print("清理后记录数：", len(clean))
print("学号唯一：", clean["学号"].is_unique)

班级
A    3
B    3
Name: count, dtype: Int64

0    True
1    True
2    True
3    True
4    True
5    True
Name: 姓名, dtype: boolean

  学号  姓名 班级 成绩      日期  分数 登记日
5  005  小吴    B   76  日期待核    76    NaT

学号      string[python]
姓名      string[python]
班级      string[python]
成绩      string[python]
日期      string[python]
分数               Int64
登记日    datetime64[ns]
dtype: object

  学号  姓名 班级 成绩        日期  分数     登记日
0  001  小林    A   82  2026-09-01    82 2026-09-01
4  001  小林    A   82  2026-09-01    82 2026-09-01

清理后记录数： 5
学号唯一： True

### 异常与缺失

输出均值前先说明有效样本；比较填零会改变什么。

In [34]:
clean["成绩异常"] = (clean["分数"].notna() &
                       ~clean["分数"].between(0, 100))
clean["有效成绩"] = clean["分数"].mask(clean["成绩异常"])
display(clean[["学号", "成绩", "成绩异常", "有效成绩"]])
print("有效成绩均值：", clean["有效成绩"].mean())

display(clean["有效成绩"].mean())
display(clean["有效成绩"].fillna(0).mean())
usable_scores = clean.dropna(subset=["有效成绩"])
display(usable_scores[["学号", "有效成绩"]])

  学号  成绩  成绩异常  有效成绩
0  001    82     False        82
1  002    95     False        95
2  003  缺考     False      <NA>
3  004   108      True      <NA>
4  005    76     False        76

有效成绩均值： 84.33333333333333

np.float64(84.33333333333333)

np.float64(50.6)

  学号  有效成绩
0  001        82
1  002        95
4  005        76

### 分级、往返与清洗汇总

cut 的边界与 map 的键需要明确；CSV读回显式保存学号类型。

In [35]:
clean["等级"] = pd.cut(clean["有效成绩"],
    bins=[0, 60, 80, 90, 101], right=False,
    labels=["待提高", "合格", "良好", "优秀"])
clean["班级名称"] = clean["班级"].map({"A": "一班", "B": "二班"})
clean[["学号", "有效成绩", "等级", "班级名称"]]

csv_text = clean.to_csv(index=False)
restored = pd.read_csv(StringIO(csv_text), dtype={"学号": "string"})
display(restored["学号"].tolist())
print(len(raw), len(clean), len(restored))
assert len(raw) == 6 and len(clean) == 5
assert restored["学号"].iloc[0] == "001"

audit = pd.Series({
    "输入行数": len(raw), "保留行数": len(clean),
    "有效成绩数": clean["有效成绩"].count(),
    "异常成绩数": clean["成绩异常"].sum(),
    "待核日期数": clean["登记日"].isna().sum()})
display(audit)

['001', '002', '003', '004', '005']

6 5 5

输入行数      6
保留行数      5
有效成绩数    3
异常成绩数    1
待核日期数    1
dtype: int64

**练习**：统计有效成绩数、缺考数、异常数，并找出有效成绩低于80的学生。

<details><summary>参考答案（先自己动手）</summary>

```python
print(clean["有效成绩"].count(), clean["成绩"].eq("缺考").sum(), clean["成绩异常"].sum())
display(clean.loc[clean["有效成绩"].lt(80).fillna(False), ["学号", "姓名", "班级", "有效成绩"]])
# 3、1、1；小吴76分。缺考不能用于判断是否低于80分。
```
</details>

### 12.2 三股风险统计（选做）

为观察较长时间的统计特征，对同三只股票构造250期价格；仅用于方法演示，不是投资预测。B仅表示工作日，252是本练习采用的年化因子。

In [36]:
rng = np.random.default_rng(42)
dates = pd.date_range("2026-01-05", periods=250, freq="B")

# 模拟三只股票的日对数收益率，再还原为价格
rets = pd.DataFrame({
    "茅台": 0.0004 + 0.015 * rng.standard_normal(250),
    "平安": 0.0002 + 0.020 * rng.standard_normal(250),
    "招行": 0.0003 + 0.018 * rng.standard_normal(250)},
    index=dates)
prices = 100 * np.exp(rets.cumsum())
prices.tail(3)

                 茅台        平安       招行
2026-12-16  89.651397  126.024709  67.261712
2026-12-17  93.681881  121.129685  66.833219
2026-12-18  92.086771  117.584889  65.787109

In [37]:
rets = prices.pct_change(fill_method=None).dropna()
display(rets.describe().round(4))
display(pd.DataFrame({"年化算术平均收益": rets.mean() * 252,
                      "年化波动率": rets.std() * np.sqrt(252)}).round(4))
display(rets.corr().round(2))

           茅台      平安      招行
count  249.0000  249.0000  249.0000
mean    -0.0003    0.0009   -0.0016
std      0.0142    0.0196    0.0185
min     -0.0313   -0.0498   -0.0517
25%     -0.0105   -0.0116   -0.0152
50%     -0.0013    0.0020   -0.0023
75%      0.0084    0.0130    0.0104
max      0.0451    0.0535    0.0473

      年化算术平均收益  年化波动率
茅台           -0.0633      0.2250
平安            0.2195      0.3112
招行           -0.4056      0.2935

      茅台  平安  招行
茅台  1.00  0.04 -0.01
平安  0.04  1.00 -0.05
招行 -0.01 -0.05  1.00

**练习**：找出每只股票最大单日跌幅及日期；用月末价格计算月间收益率。

<details><summary>参考答案（先自己动手）</summary>

```python
display(pd.DataFrame({"最小日收益率": rets.min(), "发生日期": rets.idxmin()}))
display(prices.resample("ME").last().pct_change(fill_method=None))
# 首月无前月价格，末月可能不完整；年化算术均值不等于复合年度收益。
```
</details>

### 学习检查

- 能否说明宽表、长表中每行的含义，以及缺失值保留在哪里？
- 能否区分 agg、transform、filter、apply 的输出形状？
- 能否解释连接前后行数变化、共同样本筛选和重采样标签？

阅读来源与本地数据说明见本章 [README](../README.md)。