<img src="http://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

# Python for Finance

**Analyze Big Financial Data**

O'Reilly (2014)

Yves Hilpisch

<img style="border:0px solid grey;" src="http://hilpisch.com/python_for_finance.png" alt="Python for Finance" width="30%" align="left" border="0">

**Buy the book ** |
<a href='http://shop.oreilly.com/product/0636920032441.do' target='_blank'>O'Reilly</a> |
<a href='http://www.amazon.com/Yves-Hilpisch/e/B00JCYHHJM' target='_blank'>Amazon</a>

**All book codes & IPYNBs** |
<a href="http://oreilly.quant-platform.com">http://oreilly.quant-platform.com</a>

**The Python Quants GmbH** | <a href='http://tpq.io' target='_blank'>http://tpq.io</a>

**Contact us** | <a href='mailto:pff@tpq.io'>pff@tpq.io</a>

# Data Types and Structures

## Basic Data Types

### Integers

In [40]:
a = 10
type(a)

int

In [41]:
a.bit_length()

4

In [42]:
a = 100000
a.bit_length()

17

In [43]:
googol = 10 ** 100
googol

10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

In [44]:
googol.bit_length()

333

In [45]:
1 + 4

5

In [46]:
1 / 4

0.25

In [47]:
type(1 / 4)

float

### Floats

In [48]:
1. / 4

0.25

In [49]:
type (1. / 4)

float

In [50]:
b = 0.35
type(b)

float

In [51]:
b + 0.1

0.44999999999999996

In [52]:
c = 0.5
c.as_integer_ratio()

(1, 2)

In [53]:
b.as_integer_ratio()

(3152519739159347, 9007199254740992)

In [54]:
import decimal
from decimal import Decimal

In [55]:
decimal.getcontext()

Context(prec=50, rounding=ROUND_HALF_EVEN, Emin=-999999, Emax=999999, capitals=1, clamp=0, flags=[Inexact, Rounded], traps=[InvalidOperation, DivisionByZero, Overflow])

In [56]:
d = Decimal(1) / Decimal (11)
d

Decimal('0.090909090909090909090909090909090909090909090909091')

In [57]:
decimal.getcontext().prec = 4  # lower precision than default

In [58]:
e = Decimal(1) / Decimal (11)
e

Decimal('0.09091')

In [59]:
decimal.getcontext().prec = 50  # higher precision than default

In [60]:
f = Decimal(1) / Decimal (11)
f

Decimal('0.090909090909090909090909090909090909090909090909091')

In [61]:
g = d + e + f
g

Decimal('0.27272818181818181818181818181818181818181818181818')

### Strings

In [62]:
t = 'this is a string object'

In [63]:
t.count('i')

3

In [64]:
t.capitalize()

'This is a string object'

In [65]:
t.split()

['this', 'is', 'a', 'string', 'object']

In [66]:
t.find('string')

10

In [67]:
t.find('Python')

-1

In [68]:
t.replace(' ', '|')

'this|is|a|string|object'

In [69]:
'http://www.python.org'.strip('htp:/')

'www.python.org'

In [70]:
import re

In [71]:
series = """
'01/18/2014 13:00:00', 100, '1st';
'01/18/2014 13:30:00', 110, '2nd';
'01/18/2014 14:00:00', 120, '3rd'
"""

In [72]:
dt = re.compile("'[0-9/:\s]+'")  # datetime

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\weiguan\AppData\Local\Temp\ipykernel_23484\231164877.py:1: SyntaxWarning: invalid escape sequence '\s'
  dt = re.compile("'[0-9/:\s]+'")  # datetime

In [73]:
result = dt.findall(series)
result

["'01/18/2014 13:00:00'", "'01/18/2014 13:30:00'", "'01/18/2014 14:00:00'"]

In [74]:
from datetime import datetime
pydt = datetime.strptime(result[0].replace("'", ""),
                         '%m/%d/%Y %H:%M:%S')
pydt

datetime.datetime(2014, 1, 18, 13, 0)

In [75]:
print(pydt)

2014-01-18 13:00:00

In [76]:
print(type(pydt))

<class 'datetime.datetime'>

## Basic Data Structures

### Tuples

In [118]:
t = (1, 2.5, 'data')
type(t)

tuple

In [119]:
t

(1, 2.5, 'data')

In [78]:
t[0] = 10
""" Raise TypeError: 'tuple' object does not support item assignment """

TypeError: 'tuple' object does not support item assignment

In [120]:
t = 1, 2.5, 'data'
type(t)

tuple

In [80]:
t[2]

'data'

In [81]:
type(t[2])

str

In [82]:
t.count('data')

1

In [83]:
t.index(1)

0

### Lists

In [129]:
l = [1, 2.5, 'data']
l[2]

'data'

In [130]:
l[0] = 10

In [131]:
t

(1, 2.5, 'data')

In [132]:
l = list(t)
l

[1, 2.5, 'data']

In [133]:
type(l)

list

In [134]:
l.append([3, 4])

In [135]:
l

[1, 2.5, 'data', [3, 4]]

In [136]:
 l = l + [[3, 4]]

In [137]:
l

[1, 2.5, 'data', [3, 4], [3, 4]]

In [138]:
# l = l.append([4, 3])  # Return None

In [139]:
l

[1, 2.5, 'data', [3, 4], [3, 4]]

In [140]:
l.insert(1, 'insert')  # insert object before index position
l

[1, 'insert', 2.5, 'data', [3, 4], [3, 4]]

In [141]:
l.remove('data')  # remove first occurence of object
l

[1, 'insert', 2.5, [3, 4], [3, 4]]

In [142]:
p = l.pop(3)  # removes and returns object at index
print(l, p)

[1, 'insert', 2.5, [3, 4]] [3, 4]

In [143]:
l[2:5]  # 3rd to 5th element

[2.5, [3, 4]]

In [144]:
l

[1, 'insert', 2.5, [3, 4]]

### Excursion: Control Structures

In [111]:
for element in l[2:5]:
    print(element * 2)

5.0
[3, 4, 3, 4]

In [112]:
r = range(0, 8, 1)  # start, end, step width
r

range(0, 8)

In [ ]:
type(r)

range

In [116]:
l

[1, 'insert', 2.5, [3, 4]]

In [117]:
for i in range(len(l)):
    print(l[i] * 2)

2
insertinsert
5.0
[3, 4, 3, 4]

In [ ]:
for i in range(1, 10):
    if i % 2 == 0:  # % is for modulo
        print("%d is even" % i)
    elif i % 3 == 0:
        print("%d is multiple of 3" % i)
    else:
        print("%d is odd" % i)

1 is odd
2 is even
3 is multiple of 3
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is multiple of 3

In [ ]:
total = 0
while total < 100:
    total += 1   # total = total + 1
print(total)

100

In [ ]:
m = [i ** 2 for i in range(5)]
m

m = []
for i in range(5):
    m.append(i ** 2)

[0, 1, 4, 9, 16]

### Excursion: Functional Programming

In [165]:
def f(x, y=2):
    return x ** 2
    # print(x**2)
f(2)

4

In [ ]:
def even(x):
    return x % 2 == 0
even(3)

False

In [ ]:
list(map(even, range(10)))

[True, False, True, False, True, False, True, False, True, False]

In [ ]:
list(map(lambda x: x ** 2, range(10)))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
list(filter(even, range(15)))

[0, 2, 4, 6, 8, 10, 12, 14]

### Dicts

In [ ]:
d = {
     'Name' : 'Angela Merkel',
     'Country' : 'Germany',
     'Profession' : 'Chancelor',
     'Age' : 60
     }
type(d)

dict

In [ ]:
print(d['Name'], d['Age'])

Angela Merkel 60

In [ ]:
d.keys()

dict_keys(['Name', 'Country', 'Profession', 'Age'])

In [ ]:
d.values()

dict_values(['Angela Merkel', 'Germany', 'Chancelor', 60])

In [ ]:
d.items()

dict_items([('Name', 'Angela Merkel'), ('Country', 'Germany'), ('Profession', 'Chancelor'), ('Age', 60)])

In [ ]:
birthday = True
if birthday is True:
    d['Age'] += 1
print(d['Age'])

61

In [ ]:
for item in d.items():
    print(item)

('Name', 'Angela Merkel')
('Country', 'Germany')
('Profession', 'Chancelor')
('Age', 61)

In [ ]:
for value in d.values():
    print(type(value))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'int'>

### Sets

In [ ]:
s = set(['u', 'd', 'ud', 'du', 'd', 'du'])
s

{'d', 'du', 'u', 'ud'}

In [ ]:
t = set(['d', 'dd', 'uu', 'u'])

In [ ]:
s.union(t)  # all of s and t

{'d', 'dd', 'du', 'u', 'ud', 'uu'}

In [ ]:
s.intersection(t)  # both in s and t

{'d', 'u'}

In [ ]:
s.difference(t)  # in s but not t

{'du', 'ud'}

In [ ]:
t.difference(s)  # in t but not s

{'dd', 'uu'}

In [ ]:
s.symmetric_difference(t)  # in either one but not both

{'dd', 'du', 'ud', 'uu'}

In [ ]:
from random import randint
l = [randint(0, 10) for i in range(1000)]
    # 1,000 random integers between 0 and 10
len(l)  # number of elements in l

1000

In [ ]:
l[:20]

[5, 9, 7, 4, 0, 3, 5, 2, 10, 5, 6, 1, 8, 4, 2, 8, 10, 9, 4, 6]

In [ ]:
s = set(l)
s

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

## NumPy Data Structures

### Arrays with Python Lists

In [ ]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]  # vector of numbers

In [ ]:
m = [v, v, v]  # matrix of numbers
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [ ]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [ ]:
m[1][0]

0.5

In [ ]:
v1 = [0.5, 1.5]
v2 = [1, 2]
m = [v1, v2]
c = [m, m]  # cube of numbers
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [ ]:
c[1][1][0]

1

In [ ]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [ ]:
v[0] = 'Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [ ]:
from copy import deepcopy
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = 3 * [deepcopy(v), ]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [ ]:
v[0] = 'Python'
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

### Regular NumPy Arrays

In [ ]:
import numpy as np

In [ ]:
a = np.array([0, 0.5, 1.0, 1.5, 2.0])
type(a)

numpy.ndarray

In [ ]:
a[:2]  # indexing as with list objects in 1 dimension

array([0. , 0.5])

In [ ]:
a.sum()  # sum of all elements

5.0

In [ ]:
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
a.std()  # standard deviation

0.7071067811865476

In [ ]:
a.cumsum()  # running cumulative sum

array([0. , 0.5, 1.5, 3. , 5. ])

In [ ]:
a * 2

array([0., 1., 2., 3., 4.])

In [ ]:
a ** 2

array([0.  , 0.25, 1.  , 2.25, 4.  ])

In [ ]:
np.sqrt(a)

array([0.        , 0.70710678, 1.        , 1.22474487, 1.41421356])

In [ ]:
b = np.array([a, a * 2])
b

array([[0. , 0.5, 1. , 1.5, 2. ],
       [0. , 1. , 2. , 3. , 4. ]])

In [ ]:
b[0]  # first row

array([ 0. ,  0.5,  1. ,  1.5,  2. ])

In [ ]:
b[0, 2]  # third element of first row

1.0

In [ ]:
b.sum()

15.0

In [ ]:
b.sum(axis=0)
  # sum along axis 0, i.e. column-wise sum

array([ 0. ,  1.5,  3. ,  4.5,  6. ])

In [ ]:
b.sum(axis=1)
  # sum along axis 1, i.e. row-wise sum

array([  5.,  10.])

In [ ]:
c = np.zeros((2, 3, 4), dtype='i', order='C')  # also: np.ones()
c

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [ ]:
d = np.ones_like(c, dtype='f16', order='C')  # also: np.zeros_like()
d

array([[[ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0]],

       [[ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0]]], dtype=float128)

In [ ]:
import random
I = 5000

In [ ]:
%time mat = [[random.gauss(0, 1) for j in range(I)] for i in range(I)]
  # a nested list comprehension

CPU times: user 18.1 s, sys: 380 ms, total: 18.5 s
Wall time: 18.6 s

In [ ]:
%time mat = np.random.standard_normal((I, I))

CPU times: user 1.15 s, sys: 160 ms, total: 1.31 s
Wall time: 1.31 s

In [ ]:
%time mat.sum()

CPU times: user 16.2 ms, sys: 1.39 ms, total: 17.5 ms
Wall time: 15.5 ms

-2428.7146035744513

### Structured Arrays

In [ ]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'),
               ('Height', 'f'), ('Children/Pets', 'i4', 2)])
s = np.array([('Smith', 45, 1.83, (0, 1)),
              ('Jones', 53, 1.72, (2, 2))], dtype=dt)
s

array([(b'Smith', 45,  1.83000004, [0, 1]),
       (b'Jones', 53,  1.72000003, [2, 2])],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [ ]:
s['Name']

array([b'Smith', b'Jones'],
      dtype='|S10')

In [ ]:
s['Height'].mean()

1.7750001

In [ ]:
s[1]['Age']

53

## Vectorization of Code

### Basic Vectorization

In [ ]:
l1 = [1, 2, 3]

In [ ]:
l2 = [4, 5, 6]

In [ ]:
l1+l2

[1, 2, 3, 4, 5, 6]

In [ ]:
r = np.random.standard_normal((4, 3))
s = np.random.standard_normal((4, 3))

In [ ]:
r

array([[-0.32333751,  0.35155981,  0.71560652],
       [-0.30456269,  0.89137528,  0.43345831],
       [-0.21613963,  1.15808474,  0.93319244],
       [ 0.501778  , -0.52594882, -0.35127293]])

In [ ]:
s

array([[ 0.90387431, -1.04311642, -1.57294237],
       [ 0.26768394,  1.26912853, -0.17177094],
       [ 0.6696182 ,  0.76668857,  0.35332994],
       [ 1.6670937 , -0.03960478, -0.83988927]])

In [ ]:
r + s

array([[ 0.58053679, -0.69155661, -0.85733584],
       [-0.03687875,  2.16050381,  0.26168738],
       [ 0.45347857,  1.92477332,  1.28652239],
       [ 2.1688717 , -0.5655536 , -1.1911622 ]])

In [ ]:
2 * r + 3

array([[ 1.34372288,  3.15555248,  3.9816459 ],
       [ 0.86055109,  3.74903593,  2.48469897],
       [ 2.65591344,  1.47885806,  1.316848  ],
       [ 2.05312193,  5.03535432,  3.68703385]])

In [ ]:
s = np.random.standard_normal(3)
r + s

array([[-2.39772948,  0.82536573,  0.44468374],
       [-2.63931537,  1.12210745, -0.30378972],
       [-1.7416342 , -0.01298148, -0.88771521],
       [-2.04302995,  1.76526665,  0.29737772]])

In [ ]:
# causes intentional error
# s = np.random.standard_normal(4)
# r + s

In [ ]:
# r.transpose() + s

In [ ]:
np.shape(r.T)

(3, 4)

In [ ]:
def f(x):
    return 3 * x + 5

In [ ]:
f(0.5)  # float object

6.5

In [ ]:
f(r)  # NumPy array

array([[ 2.51558433,  5.23332872,  6.47246885],
       [ 1.79082663,  6.1235539 ,  4.22704846],
       [ 4.48387017,  2.7182871 ,  2.47527199],
       [ 3.5796829 ,  8.05303149,  6.03055078]])

In [ ]:
# causes intentional error
# import math
# math.sin(r)

In [ ]:
np.sin(r)  # array as input

array([[-0.73667385,  0.07769785,  0.47135185],
       [-0.87706818,  0.36582395, -0.25480932],
       [-0.17119582, -0.68933519, -0.74569412],
       [-0.45594974,  0.85089003,  0.33680062]])

In [ ]:
np.sin(np.pi)  # float as input

1.2246467991473532e-16

## Conclusions

## Further Reading

<img src="http://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

<a href="http://tpq.io" target="_blank">http://tpq.io</a> | <a href="http://twitter.com/dyjh" target="_blank">@dyjh</a> | <a href="mailto:training@tpq.io">training@tpq.io</a>

**Quant Platform** |
<a href="http://quant-platform.com">http://quant-platform.com</a>

**Python for Finance** |
<a href="http://python-for-finance.com" target="_blank">Python for Finance @ O'Reilly</a>

**Derivatives Analytics with Python** |
<a href="http://derivatives-analytics-with-python.com" target="_blank">Derivatives Analytics @ Wiley Finance</a>

**Listed Volatility and Variance Derivatives** |
<a href="http://lvvd.tpq.io" target="_blank">Listed VV Derivatives @ Wiley Finance</a>

**Python Training** |
<a href="http://training.tpq.io" target="_blank">Python for Finance University Certificate</a>

In [ ]:
import pandas as pd

In [ ]:
df_abcd = pd.DataFrame(
    [10, 20, 30, 40],
    columns=['numbers'],
    index=['a', 'b', 'c', 'd'])

In [ ]:
df_abcd.loc[1:3]

TypeError: cannot do slice indexing on Index with these indexers [1] of type int

In [ ]:
df_abcd.iloc[1:3]

   numbers
b       20
c       30

In [ ]:
df_1234 = pd.DataFrame(
    [10, 20, 30, 40],
    columns=['numbers'],
    index=[1, 2, 3, 4])

In [ ]:
df_1234

   numbers
1       10
2       20
3       30
4       40

In [ ]:
df_1234.loc[2]

numbers    20
Name: 2, dtype: int64

In [ ]:
df_1234.iloc[2]

numbers    30
Name: 3, dtype: int64

In [ ]:
df_1234.loc[1:3]

   numbers
1       10
2       20
3       30

In [ ]:
df_1234.iloc[1:3]

   numbers
2       20
3       30

In [ ]:
def f(x):
    return x*2

In [ ]:
f(2)

4

In [ ]:
[]